language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"

before_script:
  - pear config-set preferred_state alpha
  - pear install pear/MP3_Id
  - pear install pear/MP3_IDv2

script: phpunit --configuration phpunit.xml

notifications:
  email: false