language: php
php:
  - hhvm
  - nightly
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2

before_script:
  - chmod 777 Tests/tmp
  - pear config-set preferred_state alpha
  - pear install pear/MP3_Id
  - pear install pear/MP3_IDv2
  - pear install package.xml
  - pear version
  - pear list

script: phpunit --configuration phpunit.xml

notifications:
  email: false